import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { SITE } from '@/lib/site';

const pages: Record<string, { title: string; intro: string; sections: [string, string][] }> = {
  terms: { title: 'Terms & Conditions', intro: 'These terms explain the general rules for using Discovery Cappadocia and booking travel services.', sections: [['Bookings', 'A booking is confirmed only after the required payment is accepted and a written confirmation is issued. Product-specific conditions shown at checkout form part of your agreement.'], ['Traveller responsibilities', 'You are responsible for providing accurate names, contact details, hotel and flight information, arriving at the agreed pickup point, and following safety instructions.'], ['Changes', 'Routes, pickup times and activity details may change where weather, safety, traffic or operational conditions require it.'], ['Contact', `Questions may be sent to ${SITE.email} or ${SITE.phoneDisplay}.`]] },
  'cancellation-refund': { title: 'Cancellation & Refund Policy', intro: 'Cancellation terms can vary by experience and are displayed before payment and on the booking confirmation.', sections: [['Customer cancellations', 'The cancellation deadline and any applicable fee are stated for the selected product during checkout. Requests must include the reservation number.'], ['Operator cancellations', 'If an experience cannot operate, we will offer the applicable rescheduling or refund options. Balloon flights depend on aviation and weather approval.'], ['Refund timing', 'Approved refunds are sent to the original payment method. Bank processing times are outside our control.']] },
  privacy: { title: 'Privacy Policy', intro: 'This policy describes how personal data is used to provide bookings and customer support.', sections: [['Data we collect', 'We may collect identity, contact, booking, pickup, payment reference, device and consent information. Full card details are handled by the selected payment provider and should not be stored by us.'], ['Why we use it', 'Data is used to fulfil bookings, provide support, meet legal duties, prevent fraud and, with consent, measure or improve marketing.'], ['Sharing', 'Necessary data may be shared with tour operators, transport providers, payment processors and public authorities where legally required.'], ['Your choices', `You may request information or exercise applicable data rights by emailing ${SITE.email}.`]] },
  kvkk: { title: 'KVKK / Personal Data Policy', intro: 'This notice provides general information on processing personal data under Türkiye’s personal data protection framework.', sections: [['Processing purposes', 'Personal data may be processed to create and perform reservations, communicate pickup information, fulfil legal duties and handle requests.'], ['Legal grounds', 'Processing may rely on contract performance, legal obligations, legitimate interests or explicit consent where required.'], ['Applications', `Data subject applications may be submitted to ${SITE.email}. Identity verification may be requested before responding.`]] },
  'cookie-policy': { title: 'Cookie Policy', intro: 'Cookies help operate the booking website and, when you consent, measure its performance.', sections: [['Essential cookies', 'These retain security, theme, language, currency, booking and consent preferences. They are necessary for requested services.'], ['Analytics and advertising', 'Google Tag Manager and connected measurement tools are loaded only after “Accept all” is selected and only when their identifiers are configured.'], ['Changing your choice', 'You can clear site storage in your browser to reset the consent banner.']] },
  'distance-sales': { title: 'Distance Sales Agreement', intro: 'The final distance sales agreement must be presented with the supplier identity, selected service, total, payment and cancellation terms before the customer pays.', sections: [['Pre-contract information', 'The checkout must show the exact service, date, participants, pickup, taxes, total amount, payment schedule and product-specific cancellation terms.'], ['Confirmation', 'After payment, the customer should receive a durable confirmation containing the reservation number and all agreed service details.'], ['Important', 'This page is an operational template and must be reviewed and completed by qualified Turkish counsel before production use.']] },
};

type Props = { params: { slug: string } };
export function generateStaticParams() { return Object.keys(pages).map((slug) => ({ slug })); }
export function generateMetadata({ params }: Props): Metadata { const page = pages[params.slug]; return page ? { title: page.title, description: page.intro, alternates: { canonical: `/legal/${params.slug}` } } : {}; }

export default function LegalPage({ params }: Props) {
  const page = pages[params.slug];
  if (!page) notFound();
  return <div className="min-h-screen bg-[#f8f6f1] px-4 pb-24 pt-36 dark:bg-dark"><article className="mx-auto max-w-3xl rounded-3xl border border-stone-200 bg-white p-7 shadow-sm dark:border-white/10 dark:bg-white/5 sm:p-12"><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-700 dark:text-emerald-400">{SITE.legalName} · TÜRSAB No: {SITE.tursabNumber}</p><h1 className="mt-3 font-display text-4xl font-bold sm:text-5xl">{page.title}</h1><p className="mt-5 text-lg leading-8 text-stone-600 dark:text-white/60">{page.intro}</p><p className="mt-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-900 dark:bg-amber-300/10 dark:text-amber-200">Draft for operational review. Legal language must be reviewed by qualified counsel before launch.</p><div className="mt-10 space-y-9">{page.sections.map(([title, text]) => <section key={title}><h2 className="font-display text-2xl font-bold">{title}</h2><p className="mt-3 leading-7 text-stone-600 dark:text-white/60">{text}</p></section>)}</div><p className="mt-12 border-t border-stone-200 pt-6 text-xs text-stone-400 dark:border-white/10">Last updated: 7 August 2026</p></article></div>;
}
